[package]
name = "imgcat"
version = "0.1.0"

[dependencies]
image = "0.23.11"
termimg = {path="../termimg"}
docopt = "1.0"
serde = "1.0"
serde_derive = "1.0"
seek_bufread = "1.2.2"
resvg = "0.11.0"
usvg = "0.11.0"
infer = "0.14.0"
